In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

# Target (apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

In [ ]:
# Convert inputs and targets to tensors

inputs_t = torch.from_numpy(inputs)
targets_t = torch.from_numpy(targets)

print(inputs_t)
print(targets_t)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


**3.2 Linear Regression Model (from scratch)**

In [ ]:
# Weights and biases
Weights = torch.randn(3, 1, requires_grad=True)
biases = torch.randn(1, requires_grad=True)
print(Weights)
print(biases)

tensor([[-1.1960],
        [ 0.2496],
        [-0.9904]], requires_grad=True)
tensor([-0.1791], requires_grad=True)


In [ ]:
# Define the model
def model(x):
    return x @ Weights + biases

In [ ]:
# Generate predictions
pred = model(inputs_t)
pred

tensor([[-113.3490],
        [-150.4336],
        [-128.2250],
        [-148.0801],
        [-128.0681]], grad_fn=<AddBackward0>)

In [ ]:
# Compare with targets
print(targets_t)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


**3.3 Loss Function**

In [ ]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
# Compute 

loss = mse(pred, targets_t)
print(loss)

tensor(45136.1016, grad_fn=<DivBackward0>)


**3.4 Compute Gradients**

In [ ]:
# Compute gradients
loss.backward()

In [ ]:
# Gradients for weights
print(Weights)
print(Weights.grad)

tensor([[-1.1960],
        [ 0.2496],
        [-0.9904]], requires_grad=True)
tensor([[-35289.3516],
        [-37734.6680],
        [-23560.2148]])


In [ ]:
# Gradients for bias
print(biases)
print(biases.grad)

tensor([-0.1791], requires_grad=True)
tensor([-419.6623])


In [ ]:
Weights.grad.zero_()
biases.grad.zero_()
print(Weights.grad)
print(biases.grad)

tensor([[0.],
        [0.],
        [0.]])
tensor([0.])


**3.5 Adjust weights and biases using gradient descent**

In [ ]:
# Generate predictions
pred = model(inputs_t)
print(pred)

tensor([[-113.3490],
        [-150.4336],
        [-128.2250],
        [-148.0801],
        [-128.0681]], grad_fn=<AddBackward0>)


In [ ]:
# Calculate the loss
loss = mse(pred, targets_t)
print(loss)

tensor(45136.1016, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
print(Weights.grad)
print(biases.grad)

tensor([[0.],
        [0.],
        [0.]])
tensor([0.])


In [ ]:
# Adjust weights & reset gradients
with torch.no_grad():
    Weights -= Weights.grad * 1e-5
    biases -= biases.grad * 1e-5
    Weights.grad.zero_()
    biases.grad.zero_()

In [ ]:
print(Weights)
print(biases)

tensor([[-1.1960],
        [ 0.2496],
        [-0.9904]], requires_grad=True)
tensor([-0.1791], requires_grad=True)


In [ ]:
# Calculate loss
pred = model(inputs_t)
loss = mse(pred, targets_t)
print(loss)

tensor(45136.1016, grad_fn=<DivBackward0>)


**3.6 Train for multiple epochs**

In [ ]:
# Train for 100 epochs
for i in range(160):
    pred = model(inputs_t)
    loss = mse(pred, targets_t)
    loss.backward()
    with torch.no_grad():
        Weights -= Weights.grad * 1e-5
        biases -= biases.grad * 1e-5
        Weights.grad.zero_()
        biases.grad.zero_()

In [ ]:
# Calculate loss
pred = model(inputs_t)
loss = mse(pred, targets_t)
print(loss)

tensor(67.4198, grad_fn=<DivBackward0>)


In [ ]:
# Predictions
pred

tensor([[ 57.7410],
        [ 76.4064],
        [130.9590],
        [ 23.9668],
        [ 90.1128]], grad_fn=<AddBackward0>)

In [ ]:
# Targets
targets_t

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])

**1.1 Linear Regression Model using PyTorch built-ins**

In [ ]:
# Imports
import torch.nn as nn
import torch
import numpy as np

In [ ]:
# Input (temp, rainfall, humidity)

inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70],
                   [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69,96, 70],
                   [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]],dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [ ]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[:]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [ ]:
# Define data loader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

for batch, (xb, yb) in enumerate(train_dl):
    print(f'batch: {batch+1}')
    print(xb)
    print(yb)
    print('='*40)

batch: 1
tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.]])
tensor([[ 22.,  37.],
        [103., 119.],
        [103., 119.],
        [ 22.,  37.],
        [ 56.,  70.]])
batch: 2
tensor([[ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.]])
tensor([[119., 133.],
        [ 56.,  70.],
        [ 56.,  70.],
        [103., 119.],
        [ 81., 101.]])
batch: 3
tensor([[102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]])
tensor([[ 22.,  37.],
        [119., 133.],
        [ 81., 101.],
        [119., 133.],
        [ 81., 101.]])


In [ ]:
# Define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0245,  0.0972,  0.3993],
        [ 0.5581, -0.2812,  0.3886]], requires_grad=True)
Parameter containing:
tensor([-0.0465, -0.4198], requires_grad=True)


In [ ]:
#Obtain Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0245,  0.0972,  0.3993],
         [ 0.5581, -0.2812,  0.3886]], requires_grad=True),
 Parameter containing:
 tensor([-0.0465, -0.4198], requires_grad=True)]

In [ ]:
# prediction

preds = model(inputs)
preds

tensor([[25.4265, 38.1959],
        [36.2950, 50.4985],
        [38.2726, 33.0013],
        [21.4080, 58.7976],
        [38.9297, 38.3021],
        [25.4265, 38.1959],
        [36.2950, 50.4985],
        [38.2726, 33.0013],
        [21.4080, 58.7976],
        [38.9297, 38.3021],
        [25.4265, 38.1959],
        [36.2950, 50.4985],
        [38.2726, 33.0013],
        [21.4080, 58.7976],
        [38.9297, 38.3021]], grad_fn=<AddmmBackward0>)

In [ ]:
# Loss 

# Import nn.functional
import torch.nn.functional as F

# Define loss function
loss_fn = F.mse_loss

# Calculate loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(3410.4470, grad_fn=<MseLossBackward0>)


In [ ]:
# Optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
# Train the model

def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1) % 10 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {round(loss.item(), 3)} ,{xb} , {yb}')

In [ ]:
# Fit the model
fit(250, model, loss_fn, opt, train_dl)

Epoch [10/250], Loss: 295.793 ,tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 69.,  96.,  70.]]) , tensor([[ 56.,  70.],
        [119., 133.],
        [103., 119.],
        [ 81., 101.],
        [103., 119.]])
Epoch [20/250], Loss: 368.414 ,tensor([[ 91.,  88.,  64.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.]]) , tensor([[ 81., 101.],
        [ 81., 101.],
        [ 22.,  37.],
        [103., 119.],
        [103., 119.]])
Epoch [30/250], Loss: 433.63 ,tensor([[102.,  43.,  37.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.]]) , tensor([[ 22.,  37.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 81., 101.],
        [ 56.,  70.]])
Epoch [40/250], Loss: 161.602 ,tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
   

In [ ]:
preds = model(inputs)
preds

tensor([[ 57.2192,  70.4742],
        [ 81.9321,  99.8939],
        [119.0769, 134.6692],
        [ 21.5342,  38.1296],
        [101.1797, 117.0381],
        [ 57.2192,  70.4742],
        [ 81.9321,  99.8939],
        [119.0769, 134.6692],
        [ 21.5342,  38.1296],
        [101.1797, 117.0381],
        [ 57.2192,  70.4742],
        [ 81.9321,  99.8939],
        [119.0769, 134.6692],
        [ 21.5342,  38.1296],
        [101.1797, 117.0381]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(targets.detach().numpy(),preds.detach().numpy()))

1.5250998


4 Exercise 1.1
1. Estimate the value of model parameters(weights and bias) and MSE Loss after training for
1000 epochs.
2. Take the learning rate value as 0.1 and train the model. Write in brief the impact of this
learning rate on the model.
3. Take the learning rate value as 0.0000001 and train the model. Write in brief the impact of
this learning rate on the model.
4. Plot a graph of the number of epochs vs the loss value of the model.
5. Use the model to predict crop yield for apples if temperature is 70, Rain is 34 and Humidity
is 45.
6. Write in brief about the approach used in the model generation process.

In [ ]:
# 1
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], Loss: 1.33 ,tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.]]) , tensor([[ 56.,  70.],
        [ 81., 101.],
        [ 22.,  37.],
        [103., 119.],
        [ 22.,  37.]])
Epoch [20/1000], Loss: 1.181 ,tensor([[ 73.,  67.,  43.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]]) , tensor([[ 56.,  70.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 81., 101.]])
Epoch [30/1000], Loss: 1.202 ,tensor([[102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.]]) , tensor([[ 22.,  37.],
        [ 56.,  70.],
        [ 81., 101.],
        [103., 119.],
        [ 22.,  37.]])
Epoch [40/1000], Loss: 1.226 ,tensor([[102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
       

In [ ]:
# 2
model2 = nn.Linear(3,2)
print(model2.weight)
print(model2.bias)
opt2 = torch.optim.SGD(model2.parameters(), lr=0.1)
fit(250, model2, loss_fn, opt2, train_dl)
preds = model2(inputs)
print(preds)
print(targets)
from sklearn.metrics import mean_squared_error
# print(mean_squared_error(targets.detach().numpy() ,preds.detach().numpy() ))

Parameter containing:
tensor([[ 0.1424, -0.2777,  0.5243],
        [-0.1664,  0.5662, -0.4234]], requires_grad=True)
Parameter containing:
tensor([-0.4654,  0.0177], requires_grad=True)
Epoch [10/250], Loss: nan ,tensor([[ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.]]) , tensor([[103., 119.],
        [119., 133.],
        [103., 119.],
        [ 81., 101.],
        [ 56.,  70.]])
Epoch [20/250], Loss: nan ,tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.]]) , tensor([[ 81., 101.],
        [ 22.,  37.],
        [119., 133.],
        [103., 119.],
        [ 22.,  37.]])
Epoch [30/250], Loss: nan ,tensor([[91., 88., 64.],
        [69., 96., 70.],
        [91., 88., 64.],
        [73., 67., 43.],
        [73., 67., 43.]]) , tensor([[ 81., 101.],
        [103., 119.],
        [ 81., 101.],
        [ 56.,  70.],
        [

In [ ]:
# 3
model3 = nn.Linear(3,2)
opt3 = torch.optim.SGD(model3.parameters(), lr=0.0000001)
fit(250, model3, loss_fn, opt3, train_dl)
preds = model3(inputs)
print(preds)
print(targets)
from sklearn.metrics import mean_squared_error
print(mean_squared_error(targets.detach().numpy(),preds.detach().numpy()))

Epoch [10/250], Loss: 11370.034 ,tensor([[102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.]]) , tensor([[ 22.,  37.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 56.,  70.],
        [103., 119.]])
Epoch [20/250], Loss: 10015.724 ,tensor([[73., 67., 43.],
        [91., 88., 64.],
        [73., 67., 43.],
        [73., 67., 43.],
        [91., 88., 64.]]) , tensor([[ 56.,  70.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 56.,  70.],
        [ 81., 101.]])
Epoch [30/250], Loss: 14150.841 ,tensor([[ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.]]) , tensor([[ 56.,  70.],
        [103., 119.],
        [119., 133.],
        [119., 133.],
        [ 22.,  37.]])
Epoch [40/250], Loss: 9507.54 ,tensor([[ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 9

In [ ]:
# 4
preds = model(torch.FloatTensor([70,34,45]))
preds

tensor([31.7193, 46.6385], grad_fn=<AddBackward0>)